namespace NATS.Client.Core;

/// <remarks>This is used to unsubscribe to a subject</remarks>
/// <inheritdoc/>
public record NatsUnsubscribeProps : NatsOperationProps
{
    /// <param name="subscriptionId">A unique subscription ID, previously generated by the client.</param>
    /// <inheritdoc/>
    public NatsUnsubscribeProps(int subscriptionId)
        : base(string.Empty)
    {
        SubscriptionId = subscriptionId;
    }

    /// <remarks>This is a workaround to enable a <see cref="NatsSubscribeProps"/> to be transformed to a <see cref="NatsUnsubscribeProps"/> </remarks>
    internal NatsUnsubscribeProps(string subject)
        : base(subject)
    {
        SubscriptionId = 0;
    }

    /// <summary>
    /// A unique numeric subscription ID, generated by the client.
    /// </summary>
    public int SubscriptionId { get; set; }
}
