using NATS.Client.Core;
using NATS.Client.JetStream.Models;

namespace NATS.Client.JetStream;

/// <summary>
/// Options for creating a push consumer.
/// </summary>
/// <remarks>
/// A push consumer delivers messages to a client subscription on a
/// <see cref="ConsumerConfig.DeliverSubject"/>. The subject is generated by the
/// <see cref="NatsJSContext"/> when the consumer is created unless the consumer already
/// has a deliver subject (for example when it is bound to an existing durable consumer).
/// </remarks>
public record NatsJSPushConsumerOpts
{
    /// <summary>
    /// Default push consumer options.
    /// </summary>
    public static readonly NatsJSPushConsumerOpts Default = new();

    /// <summary>
    /// A unique name for the consumer.
    /// </summary>
    /// <remarks>
    /// If neither <see cref="Name"/> nor <see cref="DurableName"/> is set, the consumer
    /// will be ephemeral with a generated name.
    /// </remarks>
    public string? Name { get; init; }

    /// <summary>
    /// A unique name for a durable consumer.
    /// </summary>
    public string? DurableName { get; init; }

    /// <summary>
    /// The delivery subject for the push consumer. The server uses this subject
    /// to deliver messages to the client. When not set, a new inbox is generated.
    /// </summary>
    public string? DeliverSubject { get; init; }

    /// <summary>
    /// A short description of the purpose of this consumer.
    /// </summary>
    public string? Description { get; init; }

    /// <summary>
    /// Filter the stream by a single subject.
    /// </summary>
    public string? FilterSubject { get; init; }

    /// <summary>
    /// Filter the stream by multiple subjects.
    /// </summary>
    public ICollection<string>? FilterSubjects { get; init; }

    /// <summary>
    /// Defines the start position of a consumer.
    /// </summary>
    /// <remarks>
    /// Defaults to <see cref="ConsumerConfigDeliverPolicy.All"/>.
    /// </remarks>
    public ConsumerConfigDeliverPolicy DeliverPolicy { get; init; } = ConsumerConfigDeliverPolicy.All;

    /// <summary>
    /// Start sequence for <see cref="DeliverPolicy"/> <c>ByStartSequence</c>.
    /// </summary>
    public ulong OptStartSeq { get; init; }

    /// <summary>
    /// Start time for <see cref="DeliverPolicy"/> <c>ByStartTime</c>.
    /// </summary>
    public DateTimeOffset OptStartTime { get; init; }

    /// <summary>
    /// Acknowledgment policy for the consumer.
    /// </summary>
    /// <remarks>
    /// Defaults to <see cref="ConsumerConfigAckPolicy.Explicit"/> which requires every
    /// received message to be acknowledged manually. Set to
    /// <see cref="ConsumerConfigAckPolicy.None"/> for no acknowledgments and
    /// <see cref="ConsumerConfigAckPolicy.All"/> to acknowledge all delivered messages at once.
    /// </remarks>
    public ConsumerConfigAckPolicy AckPolicy { get; init; } = ConsumerConfigAckPolicy.Explicit;

    /// <summary>
    /// How long to allow messages to remain unacknowledged before attempting a redelivery.
    /// </summary>
    public TimeSpan AckWait { get; init; }

    /// <summary>
    /// The number of times a message will be redelivered to consumers if not acknowledged in time.
    /// </summary>
    public long MaxDeliver { get; init; }

    /// <summary>
    /// The maximum number of messages without acknowledgement that can be outstanding.
    /// </summary>
    public long MaxAckPending { get; init; }

    /// <summary>
    /// A duration instructing the server to clean up the consumer once the deliver subject
    /// has no interest for that amount of time.
    /// </summary>
    /// <remarks>
    /// If not set, ephemeral consumers (no <see cref="Name"/> or <see cref="DurableName"/>)
    /// are automatically deleted by the server roughly 5 seconds after the deliver subject
    /// loses interest (for example when the client unsubscribes or disconnects for longer
    /// than the threshold). Durable consumers are never deleted automatically unless this
    /// value is set. Set to <see cref="TimeSpan.Zero"/> to explicitly disable the deletion
    /// of a durable consumer.
    /// </remarks>
    public TimeSpan? InactiveThreshold { get; init; }

    /// <summary>
    /// Amount of idle time the server should wait before sending a heartbeat.
    /// </summary>
    /// <remarks>
    /// When not set, the server does not send heartbeats.
    /// </remarks>
    public TimeSpan? IdleHeartbeat { get; init; }

    /// <summary>
    /// Sends a control message to the consumer's deliver subject to regulate the rate of message delivery.
    /// </summary>
    /// <remarks>
    /// When <c>true</c> the server will send flow control messages with a command status
    /// header and a reply subject when the consumer's delivery buffer is getting full. The
    /// client must respond to these messages to continue receiving messages. Defaults to
    /// <c>false</c>.
    /// </remarks>
    public bool FlowControl { get; init; }

    /// <summary>
    /// The name of a deliver group (queue) for load balancing across multiple subscribers.
    /// </summary>
    /// <remarks>
    /// Messages are distributed among all subscribers in the same <c>deliver_group</c>.
    /// </remarks>
    public string? DeliverGroup { get; init; }

    /// <summary>
    /// When <c>true</c>, deliver only the headers of messages, adding a
    /// <c>Nats-Msg-Size</c> header with the size of the removed payload.
    /// </summary>
    public bool HeadersOnly { get; init; }

    /// <summary>
    /// Options affecting the underlying subscription created for the delivery subject.
    /// </summary>
    public NatsSubOpts? SubOpts { get; init; }

    /// <summary>
    /// A handler function invoked for notifications related to consumption, allowing custom handling of
    /// operational updates or state changes during the consumer's lifecycle.
    /// </summary>
    public Func<INatsJSNotification, CancellationToken, Task>? NotificationHandler { get; init; }
}
