name: Release

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  nuget:
    name: dotnet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate tag
        run: |
          tag="${GITHUB_REF_NAME}"
          version="${tag#v}"
          file_version="$(head -n 1 version.txt)"
          if [ "$version" != "$file_version" ]; then
            echo "::error::Tag version ($version) does not match version.txt ($file_version)"
            exit 1
          fi

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            8.x

      - name: Pack
        # https://learn.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg
        # https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/
        run: dotnet pack -c Release -o dist -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:ContinuousIntegrationBuild=true

      - name: Push
        run: |
          cd dist
          ls -lh
          dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k "${{ secrets.NUGET_API_KEY }}" --skip-duplicate
